### ISSUE TITLE
Identify wallet

### ISSUE THREAD

**Issue by Z3r0XG** [jackmatt2/koinly-csv-exporter#3]
Hello, is it possible to add a column to separate transactions by wallet? That way, when you import it into another site, you can import to a specific wallet.  I went through the json data, but I was not sure which field is the right one to add.

**Comment by jackmatt2** [comment]
I added an extra script that should do what you want.  Let me know if it works for you.

**Comment by Z3r0XG** [comment]
Hi, thanks for this! Tried it out, it creates one file for the first wallet in the array. Assuming there is a bug somewhere that does not include all wallets in the file, or were there supposed to be multiple downloads, one for each wallet?

**Comment by jackmatt2** [comment]
Yes, it should ask you to download multiple times. There are separate CSV files per wallet

**Comment by jackmatt2** [comment]
@Z3r0XG did it work for you in the end?

**Comment by jackmatt2** [comment]
Script added to export multiple CSV files per wallet
