### ISSUE TITLE
To and from wallets

### ISSUE THREAD

**Issue by Jaakuice** [jackmatt2/koinly-csv-exporter#4]
Im a coding novice so hopefully its something easy. In the scripts-single-csv.js i've edited it to grab where the transactions are from and to. 
t.from ? t.from.wallet.name : '',
t.from ? t.from.wallet.wallet_service.name : '',
t.from ? t.from.wallet.wallet_service.type : '',
t.to ? t.to.wallet.name : '',
t.to ? t.to.wallet.wallet_service.name : '',
t.to ? t.to.wallet.wallet_service.type : '',
i've added headers but it doesn't like it, and i have no idea what i have done incorrectly.I get an "Uncaught (in promise) TypeError: t.from.wallet.wallet_service is null" How do i get the script to ignore Null values.
Many Thanks

**Comment by Jaakuice** [comment]
t.from && t.from.wallet ? t.from.wallet.name : '',
t.from && t.from.wallet && t.from.wallet.wallet_service ? t.from.wallet.wallet_service.name : '',
t.from && t.from.wallet && t.from.wallet.wallet_service ? t.from.wallet.wallet_service.type : '',
t.to && t.to.wallet ? t.to.wallet.name : '',
t.to && t.to.wallet && t.to.wallet.wallet_service ? t.to.wallet.wallet_service.name : '',
t.to && t.to.wallet && t.to.wallet.wallet_service ? t.to.wallet.wallet_service.type : '',

**Comment by jackmatt2** [comment]
Yep this should work.  If you're using a modern browser you can also use Optional Chaining.  This will make the script a little nicer

 t.from?.wallet?.name
